[package]
name = "prr"
description = "Mailing list style code reviews for github"
license-file = "LICENSE"
repository = "https://github.com/danobi/prr"
version = "0.5.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
async-trait = "0.1.57"
clap = { version = "3.1", features = ["derive"] }
gitlab = "~0.1502.0" # Does not follow semver so lock the version.
lazy_static = "1.4"
octocrab = "0.15"
regex = "1.5"
reqwest = "0.11"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tokio = { version = "1.17", default-features = false, features = ["macros", "rt-multi-thread"] }
toml = "0.5"
xdg = "2.4"
